import {
  Archive,
  Armchair,
  Baby,
  Bath,
  BedDouble,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Car,
  ChefHat,
  DoorOpen,
  Droplets,
  Dumbbell,
  Flame,
  Flower2,
  Gamepad2,
  Hammer,
  Home,
  House,
  KeyRound,
  Lamp,
  Lightbulb,
  Music,
  Package,
  Palette,
  Plug,
  Refrigerator,
  Shirt,
  ShowerHead,
  Sofa,
  Sun,
  Toilet,
  Trees,
  Tv,
  Utensils,
  Warehouse,
  WashingMachine,
  Wind,
  Wrench,
} from "lucide-react";
import type { RoomIconName } from "../model/types";

const roomIconMap = {
  living: Armchair,
  bed: BedDouble,
  kitchen: ChefHat,
  bath: Bath,
  shower: ShowerHead,
  toilet: Toilet,
  lamp: Lamp,
  sofa: Sofa,
  tv: Tv,
  dining: Utensils,
  fridge: Refrigerator,
  laundry: WashingMachine,
  closet: Shirt,
  nursery: Baby,
  office: Briefcase,
  library: BookOpen,
  gym: Dumbbell,
  garage: Car,
  garden: Trees,
  balcony: Flower2,
  storage: Warehouse,
  entry: DoorOpen,
  hall: KeyRound,
  home: Home,
  house: House,
  building: Building2,
  boxes: Boxes,
  archive: Archive,
  package: Package,
  music: Music,
  game: Gamepad2,
  studio: Palette,
  workshop: Hammer,
  tools: Wrench,
  electric: Plug,
  light: Lightbulb,
  water: Droplets,
  heat: Flame,
  vent: Wind,
  sun: Sun,
};

export const roomIconLabels: Record<RoomIconName, string> = {
  living: "Гостиная",
  bed: "Спальня",
  kitchen: "Кухня",
  bath: "Ванная",
  shower: "Душевая",
  toilet: "Санузел",
  lamp: "Свет",
  sofa: "Диванная",
  tv: "ТВ-зона",
  dining: "Столовая",
  fridge: "Холодильник",
  laundry: "Прачечная",
  closet: "Гардероб",
  nursery: "Детская",
  office: "Кабинет",
  library: "Библиотека",
  gym: "Спортзал",
  garage: "Гараж",
  garden: "Сад",
  balcony: "Балкон",
  storage: "Кладовая",
  entry: "Вход",
  hall: "Холл",
  home: "Дом",
  house: "Коттедж",
  building: "Здание",
  boxes: "Коробки",
  archive: "Архив",
  package: "Упаковка",
  music: "Музыка",
  game: "Игровая",
  studio: "Студия",
  workshop: "Мастерская",
  tools: "Инструменты",
  electric: "Электрика",
  light: "Освещение",
  water: "Вода",
  heat: "Отопление",
  vent: "Вентиляция",
  sun: "Солнце",
};

export const roomIcons = Object.keys(roomIconMap) as RoomIconName[];

export function RoomIcon({ icon }: { icon: RoomIconName | undefined }) {
  const Icon = icon && icon in roomIconMap ? roomIconMap[icon] : roomIconMap.living;

  return <Icon />;
}
